updates for roihu

diff --git a/a-access b/a-access
--- a/a-access
+++ b/a-access
@@ -4,10 +4,6 @@
 user=($USER)
 
 
-#read static variables
-inst_root="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
-source $inst_root/a_env_conf
-source $inst_root/allas-lib
 
 #local variables
 print_help=0
@@ -18,6 +14,10 @@ remove_read_project=""
 remove_write_project=""
 mode="swift"
 
+#read static variables
+inst_root="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
+source $inst_root/a_env_conf
+source $inst_root/allas-lib
 
 # read customer defaults
 if [[ -e $HOME/.a_tools_conf ]]; then
@@ -43,7 +43,6 @@ do
                ;;
               '+w' | '+write' )
                   add_write_project="$2"
-
                   shift
                   shift
                ;;
@@ -77,6 +76,11 @@ do
                   public=-1
                   shift
                 ;;
+               '-S' | '--s3' )
+                  mode="s3cmd"
+                  storage_server="s3allas"
+                  shift
+                ;;   
                '--help' | '-h' )
                   print_help=(1)
                   shift
@@ -165,19 +169,13 @@ if [[ $silent -eq 0 ]]; then
    fi
 fi 
 
-if [[ $mode != "swift" ]]; then
-   echo "This tool can be used only for managing access control for swift based object storage services"
-   echo "For S3 based services, like Lumo-o or s3allas, you need to use other access control tools, e.g. s3cmd setacl."
-   exit 1
-fi
-
-
 
 #Check that bucket exists
-bnrows=$(swift stat $bucket 2> /dev/null | wc -l )
+bnrows=$(rclone lsd ${storage_server}: | grep -c -w "$bucket")
+
 if [[ $bnrows -eq 0 ]]; then
-   echo "Bucket $bucket was not found in your current Allas project!"
-   exit 1
+     echo "Bucket $bucket was not found in your current Allas project!"
+     exit 1
 fi
 
 
@@ -186,29 +184,60 @@ fi
 project_label=$(echo ${os_project_name} |  sed -e s/"project_"/""/g)
 
 
-# check connection
-check_swift_connection
 
-## Make sure that user project has read and write permissions
-if [[  $add_read_project != "" || $add_write_project != "" ]]; then
-  user_read=$(swift stat $bucket | awk '{ if ($1=="Read") if ($2=="ACL:") print $3}'| grep -c "${OS_PROJECT_NAME}")
-  if [[ $user_read -lt 1 ]];then
-    read_acl=$(swift stat $bucket | awk '{ if ($1=="Read") if ($2=="ACL:") print $3}' |  sed -e s/"${OS_PROJECT_NAME}:\*"/""/g )
-    read_acl="${OS_PROJECT_NAME}:*,$read_acl"
-    swift post "$bucket" -r "${read_acl}"
-    bnrows=$(swift stat "${bucket}_segments" | wc -l 2> /dev/null )
-    if [[ $bnrows -eq 0 ]]; then
-        echo "Creating bucket: ${bucket}_segments in case over 5 GB files will be uploaded to the bucket."
-        rclone mkdir "${storage_server}:${bucket}_segments"
+##
+# acl in swift
+##
+if [[ $mode == "swift" ]]; then
+  # check connection
+  check_swift_connection
+
+  ## Make sure that user project has read and write permissions
+  if [[  $add_read_project != "" || $add_write_project != "" ]]; then
+    user_read=$(swift stat $bucket | awk '{ if ($1=="Read") if ($2=="ACL:") print $3}'| grep -c "${OS_PROJECT_NAME}")
+    if [[ $user_read -lt 1 ]];then
+      read_acl=$(swift stat $bucket | awk '{ if ($1=="Read") if ($2=="ACL:") print $3}' |  sed -e s/"${OS_PROJECT_NAME}:\*"/""/g )
+      read_acl="${OS_PROJECT_NAME}:*,$read_acl"
+      swift post "$bucket" -r "${read_acl}"
+      bnrows=$(swift stat "${bucket}_segments" | wc -l 2> /dev/null )
+      if [[ $bnrows -eq 0 ]]; then
+           echo "Creating bucket: ${bucket}_segments in case over 5 GB files will be uploaded to the bucket."
+           rclone mkdir "${storage_server}:${bucket}_segments"
+      fi
+      swift post "${bucket}_segments" -r "${read_acl}" 2> /dev/null
     fi
-    swift post "${bucket}_segments" -r "${read_acl}" 2> /dev/null
+
+    user_write=$(swift stat $bucket | awk '{ if ($1=="Write") if ($2=="ACL:") print $3}'| grep -c "${OS_PROJECT_NAME}")
+    if [[ $user_write -lt 1 ]]; then
+       write_acl=$(swift stat $bucket | awk '{ if ($1=="Write") if ($2=="ACL:") print $3}' |  sed -e s/"${OS_PROJECT_NAME}:\*"/""/g )
+       write_acl="${OS_PROJECT_NAME}:*,$write_acl"
+       echo "swift post $bucket -w ${write_acl}"
+       swift post "$bucket" -w "${write_acl}"
+       bnrows=$(swift stat "${bucket}_segments" | wc -l 2> /dev/null )
+       if [[ $bnrows -eq 0 ]]; then
+           echo "Creating bucket: ${bucket}_segments in case over 5 GB files will be uploaded to the bucket."
+           rclone mkdir "${storage_server}:${bucket}_segments"
+       fi
+     swift post "${bucket}_segments" -w "${write_acl}" 2> /dev/null
+    fi
   fi
 
-  user_write=$(swift stat $bucket | awk '{ if ($1=="Write") if ($2=="ACL:") print $3}'| grep -c "${OS_PROJECT_NAME}")
-  if [[ $user_write -lt 1 ]]; then
-     write_acl=$(swift stat $bucket | awk '{ if ($1=="Write") if ($2=="ACL:") print $3}' |  sed -e s/"${OS_PROJECT_NAME}:\*"/""/g )
-     write_acl="${OS_PROJECT_NAME}:*,$write_acl"
-     echo "swift post $bucket -w ${write_acl}"
+  ### Add new settings
+  if  [[ $add_read_project != "" ]] ; then
+     read_acl=$(swift stat $bucket | awk '{ if ($1=="Read") if ($2=="ACL:") print $3}' |  sed -e s/"${add_read_project}:\*"/""/g )
+     read_acl="${add_read_project}:*,$read_acl"
+     swift post "$bucket" -r "${read_acl}"
+     bnrows=$(swift stat "${bucket}_segments" | wc -l 2> /dev/null )
+     if [[ $bnrows -eq 0 ]]; then
+         echo "Creating bucket: ${bucket}_segments in case over 5 GB files will be uploaded to the bucket."
+         rclone mkdir "${storage_server}:${bucket}_segments"
+     fi
+     swift post "${bucket}_segments" -r "${read_acl}" 2> /dev/null
+  fi
+
+  if  [[ $add_write_project != "" ]] ; then
+     write_acl=$(swift stat $bucket | awk '{ if ($1=="Write") if ($2=="ACL:") print $3}' |  sed -e s/"${add_read_project}:\*"/""/g )
+     write_acl="${add_write_project}:*,$write_acl"
      swift post "$bucket" -w "${write_acl}"
      bnrows=$(swift stat "${bucket}_segments" | wc -l 2> /dev/null )
      if [[ $bnrows -eq 0 ]]; then
@@ -217,74 +246,75 @@ if [[  $add_read_project != "" || $add_write_project != "" ]]; then
      fi
      swift post "${bucket}_segments" -w "${write_acl}" 2> /dev/null
   fi
-fi
 
-### Add new settings
-if  [[ $add_read_project != "" ]] ; then
-   read_acl=$(swift stat $bucket | awk '{ if ($1=="Read") if ($2=="ACL:") print $3}' |  sed -e s/"${add_read_project}:\*"/""/g )
-   read_acl="${add_read_project}:*,$read_acl"
-   swift post "$bucket" -r "${read_acl}"
-   bnrows=$(swift stat "${bucket}_segments" | wc -l 2> /dev/null )
-   if [[ $bnrows -eq 0 ]]; then
-       echo "Creating bucket: ${bucket}_segments in case over 5 GB files will be uploaded to the bucket."
-       rclone mkdir "${storage_server}:${bucket}_segments"
-   fi
-   swift post "${bucket}_segments" -r "${read_acl}" 2> /dev/null
-fi
+  if  [[ $remove_read_project != "" ]] ; then
+     read_acl=$(swift stat $bucket | awk '{ if ($1=="Read") if ($2=="ACL:") print $3}' |  sed -e s/"${remove_read_project}:\*"/""/g )
+     swift post "$bucket" -r "${read_acl}"
+     swift post "${bucket}_segments" -r "${read_acl}" 2> /dev/null
+  fi
 
-if  [[ $add_write_project != "" ]] ; then
-   write_acl=$(swift stat $bucket | awk '{ if ($1=="Write") if ($2=="ACL:") print $3}' |  sed -e s/"${add_read_project}:\*"/""/g )
-   write_acl="${add_write_project}:*,$write_acl"
-   swift post "$bucket" -w "${write_acl}"
-   bnrows=$(swift stat "${bucket}_segments" | wc -l 2> /dev/null )
-   if [[ $bnrows -eq 0 ]]; then
-       echo "Creating bucket: ${bucket}_segments in case over 5 GB files will be uploaded to the bucket."
-       rclone mkdir "${storage_server}:${bucket}_segments"
-   fi
-   swift post "${bucket}_segments" -w "${write_acl}" 2> /dev/null
-fi
+  if  [[ $remove_write_project != "" ]] ; then
+     write_acl=$(swift stat $bucket | awk '{ if ($1=="Write") if ($2=="ACL:") print $3}' |  sed -e s/"${remove_write_project}:\*"/""/g )
+     swift post "$bucket" -w "${write_acl}"
+     swift post "${bucket}_segments" -w "${write_acl}" 2> /dev/null
+  fi
 
-if  [[ $remove_read_project != "" ]] ; then
-   read_acl=$(swift stat $bucket | awk '{ if ($1=="Read") if ($2=="ACL:") print $3}' |  sed -e s/"${remove_read_project}:\*"/""/g )
-   swift post "$bucket" -r "${read_acl}"
-   swift post "${bucket}_segments" -r "${read_acl}" 2> /dev/null
-fi
-
-if  [[ $remove_write_project != "" ]] ; then
-   write_acl=$(swift stat $bucket | awk '{ if ($1=="Write") if ($2=="ACL:") print $3}' |  sed -e s/"${remove_write_project}:\*"/""/g )
-   swift post "$bucket" -w "${write_acl}"
-   swift post "${bucket}_segments" -w "${write_acl}" 2> /dev/null
-fi
-
-if [[ $public -gt 0 ]];then
-    read_acl=$(swift stat $bucket | awk '{ if ($1=="Read") if ($2=="ACL:") print $3}' | sed -e s/".rlistings"/""/g| sed -e s/".r:\*"/""/g )
-    if [[ $read_acl == "" ]]; then
-         read_acl='.r:*,.rlistings'
-    else
+  if [[ $public -gt 0 ]];then
+     read_acl=$(swift stat $bucket | awk '{ if ($1=="Read") if ($2=="ACL:") print $3}' | sed -e s/".rlistings"/""/g| sed -e s/".r:\*"/""/g )
+     if [[ $read_acl == "" ]]; then
+          read_acl='.r:*,.rlistings'
+     else
          read_acl=${read_acl}',.r:*,.rlistings'
-    fi
-    swift post "$bucket" -r "${read_acl}"
-    bnrows=$(swift stat "${bucket}_segments" | wc -l 2> /dev/null )
-    if [[ $bnrows -eq 0 ]]; then
+     fi
+     swift post "$bucket" -r "${read_acl}"
+     bnrows=$(swift stat "${bucket}_segments" | wc -l 2> /dev/null )
+     if [[ $bnrows -eq 0 ]]; then
        echo "Creating bucket: ${bucket}_segments in case over 5 GB files will be uploaded to the bucket."
        rclone mkdir "${storage_server}:${bucket}_segments"
-    fi
-    swift post "${bucket}_segments" -r "${read_acl}" 2> /dev/null
+     fi
+      swift post "${bucket}_segments" -r "${read_acl}" 2> /dev/null
+  fi
+  if [[ $public -lt 0 ]];then
+      read_acl=$(swift stat $bucket | awk '{ if ($1=="Read") if ($2=="ACL:") print $3}' | sed -e s/".rlistings"/""/g| sed -e s/".r:\*"/""/g )
+      echo $read_acl
+      swift post "$bucket" -r "${read_acl}"
+      swift post "${bucket}_segments" -r "${read_acl}" 2> /dev/null
+  fi
+
+
+  echo "----------------------------------------------------------"
+  echo "Projects that have read access to bucket $bucket:"
+  swift stat $bucket | awk '{ if ($1=="Read") if ($2=="ACL:") print $3}' | sed -e s/".r:\*"/"Public access"/g | sed -e s/".rlistings,"/""/g | sed -e s/".rlistings"/""/g | tr "," "\n" | tr -d ":,*" | awk '{ print "  "$0}'
+  echo "----------------------------------------------------------"
+  echo "Projects that have write access to bucket $bucket:"
+  swift stat $bucket | awk '{ if ($1=="Write") if ($2=="ACL:") print $3}' | tr "," "\n" | tr -d ":,*" | awk '{ print "  "$0}'
+  echo "----------------------------------------------------------"
+
 fi
-if [[ $public -lt 0 ]];then
-    read_acl=$(swift stat $bucket | awk '{ if ($1=="Read") if ($2=="ACL:") print $3}' | sed -e s/".rlistings"/""/g| sed -e s/".r:\*"/""/g )
-    echo $read_acl
-    swift post "$bucket" -r "${read_acl}"
-    swift post "${bucket}_segments" -r "${read_acl}" 2> /dev/null
-fi
 
-
-echo "----------------------------------------------------------"
-echo "Projects that have read access to bucket $bucket:"
-swift stat $bucket | awk '{ if ($1=="Read") if ($2=="ACL:") print $3}' | sed -e s/".r:\*"/"Public access"/g | sed -e s/".rlistings,"/""/g | sed -e s/".rlistings"/""/g | tr "," "\n" | tr -d ":,*" | awk '{ print "  "$0}'
-echo "----------------------------------------------------------"
-echo "Projects that have write access to bucket $bucket:"
-swift stat $bucket | awk '{ if ($1=="Write") if ($2=="ACL:") print $3}' | tr "," "\n" | tr -d ":,*" | awk '{ print "  "$0}'
-echo "----------------------------------------------------------"
-
+##
+if [[ $mode == "s3cmd" ]]; then
+   if [[  $add_read_project != "" || $add_write_project != "" ]]; then
+        s3cmd setacl --acl-grant=read:$add_read_project s3://$bucket
+        s3cmd setacl --recursive --acl-grant=read:$add_read_project s3://$bucket
+   fi
+   if [[ $add_write_project != "" ]]; then
+        s3cmd setacl --acl-grant=read:$add_read_project s3://$bucket
+        s3cmd setacl --recursive --acl-grant=write:$add_read_project s3://$bucket
+   fi
+   if [[ $remove_read_project != "" ]] ; then
+        s3cmd setacl --recursive --acl-revoke=read:$add_read_project s3://$bucket
+        s3cmd setacl --acl-revoke=read:$add_read_project s3://$bucket
+   fi
+   if [[ $remove_wrirte_project != "" ]] ; then
+        s3cmd setacl --recursive --acl-revoke=write:$add_read_project s3://$bucket
+        s3cmd setacl --acl-revoke=write:$add_read_project s3://$bucket
+   fi
+   if [[ $public -gt 0 ]];then
+        s3cmd modify --recursive --acl-public s3://$bucket
+   fi
+   if [[ $public -lt 0 ]];then
+        s3cmd modify --recursive --acl-private s3://$bucket
+   fi
+fi 
 exit
