Compression is no longer done by default in a-put

diff --git a/a-put b/a-put
--- a/a-put
+++ b/a-put
@@ -103,7 +103,7 @@ filelist_level=0
 cumulative_size=0
 override_mode=0
 asis_mode=0
-compression=1
+compression=0
 tar_extra_options=""
 encrypt=""
 all_keys=""
@@ -155,7 +155,7 @@ do
                   shift
                   shift
                 ;;
-            '--s3cmd' )
+            '--s3cmd' | '--s3' | '-S' )
                   mode=("s3cmd")
                   shift
                 ;;
@@ -329,6 +329,10 @@ By default this tool performs following operations:
 4. By default the  data is uploaded to Allas using rclone command 
    and swift protocol. S3 protocol is available too.
 
+NOTE! Data was compression with zstdmt command is no longer done by 
+default before the upload.
+
+
 The location were data is stored in Allas can be defined with 
 options --bucket (-b) and --object (-o).
 
@@ -384,11 +388,16 @@ a-put command line options:
 -o, --object <object_name>  Define a name for the new object to be 
                             created.
 
---s3cmd                     Use s3cmd protocol in stead of swift 
-                            protocol for upoload
+-S, --s3cmd                 Use S3 protocol in stead of swift protocol 
+                            for upoload.
 
 -n, --nc                    Do not compress the data that will be uploaded.
+                            (This is now the default mode thus this option is 
+                            no longer needed).
 
+-c, --compress              The data is compressed using zstdmt command before
+                            upload. 
+ 
 -h, --help                  Print this help.
 
 -t, --tmpdir                Define a direcrory that will be used to store 
@@ -435,11 +444,12 @@ a-put command line options:
 
 --pk, --public-key          Public key used for crypt4gh encryption.
 
---sdx                       Upload data to allas in SD-connect compatible format. The 
-                            files are ecrypted with crypt4gh using CSC public key after which 
-                            the files are inported to Allas as individual objects as in 
-                            --asis format. With --public-key you can do the encryption with both
-                            csc and your own data. By default data is stored to bucket with name:
+--sdx                       Upload data to Allas in format format that is compatible with
+                            the CSC Sensitive data services: The files are encrypted with 
+                            crypt4gh using CSC public key after which the files are inported 
+                            to Allas as individual objects as in --asis format. 
+                            With --public-key you can do the encryption with both
+                            CSC and your own public key. By default data is stored to bucket with name:
                             your-projecyt-number_SD-CONNECT,
 
 
@@ -457,30 +467,28 @@ if [[ $silent -eq 0 ]]; then
    fi
 fi 
 
-#Assign project to be used if not defined 
-if [[ $os_project_name == "" ]]
-then
-  if [ -e $HOME/.allas_default ]
-  then
-     source $HOME/.allas_default
-  else
-     echo "Default project is not defined"
-     source $allas_conf_path -user $user
-     echo "os_project_name=$OS_PROJECT_NAME" > $HOME/.allas_default
-     echo "Default allas project is stored to  \$HOME/.allas_default"
-     echo ""
-  fi
-  source $HOME/.allas_default
-fi
+##Assign project to be used if not defined 
+#if [[ $os_project_name == "" ]]
+#then
+#  if [ -e $HOME/.allas_default ]
+#  then
+#     source $HOME/.allas_default
+#  else
+#     echo "Default project is not defined"
+#     source $allas_conf_path -user $user
+#     echo "os_project_name=$OS_PROJECT_NAME" > $HOME/.allas_default
+#     echo "Default allas project is stored to  \$HOME/.allas_default"
+#     echo ""
+#  fi
+#  source $HOME/.allas_default
+#fi
 
 
 #Check if zstdmt is needed and available
 if [[ $compression -eq 1 ]]; then
    if [[ $(which zstdmt 2> /dev/null | wc -l ) -ne 1 ]];then
       echo "Compression command: zstdmt is not available"
-      echo "Please install zstdmt or use option --nc:"
-      echo "  a-put --nc "
-      echo "to skip zstdmt compression during upload."
+      echo "Please install zstdmt or use a-put without compression"
       exit 1
    fi
 fi
@@ -1085,64 +1093,38 @@ dmku3fKA/wrOpWntUTkkoQvknjZDisdmSwU4oFk/on0=
   fi 
 
 
-  #upload
-  if [[ $mode == "swift" ]]
-  then
-    #Check if connection works
-    test=$(rclone about ${storage_server}: 2> /dev/null | wc -l)
-    #test=$(swift stat 2> /dev/null | grep -c "Account:")
-    
-    if [[ $test -lt 1 ]]
-    then 
-      # 
-      if [[ -n "$OS_PASSWORD" ]]; then      
-         echo "Updateting token"
-         source $allas_conf_path -user $user -k $OS_PROJECT_NAME -f 
-      fi
-      test=$(rclone about ${storage_server}: 2> /dev/null | wc -l)
-      if [[ $test -lt 1 ]]
-      then 
-        echo "No connection to Allas!"
-        echo "Please try setting the the connection again."
-        exit 1
-      fi
-    fi 
+ 
+  if [[ $silent -eq 0 ]] ; then
+     echo "Uploading data to allas."
   fi
-
-    if [[ $silent -eq 0 ]] ; then
-      echo "Uploading data to allas."
-    fi
     
-    #S3 protocol reaqures that directory exist before copyinmg
-    if [[ $mode == "s3cmd" ]]; then
-       rclone mkdir  ${storage_server}:${bucket_name}
-    fi
+  #S3 protocol reaqures that directory exist before copyinmg
+  if [[ $mode == "s3cmd" ]]; then
+     rclone mkdir  ${storage_server}:${bucket_name}
+  fi
     
-    # echo "rclone copy --progress ./$tmp_file ${storage_server}:${bucket_name}/${partial_path}"
-    if [[ $silent -eq 0 ]] ; then
-        if [[ $compression -eq 1 ]] ; then
-          #echo "rclone copy --progress ${tmp_dir}/$tmp_file ${storage_server}:${bucket_name}/${partial_path}" 
-          rclone copy --progress ${tmp_dir}/$tmp_file ${storage_server}:${bucket_name}/${partial_path}
-          exitcode=$?
-          #echo 
-        else  
-          # echo "rclone copy -L --progress ${tmp_dir}/$tmp_file ${storage_server}:${bucket_name}/${partial_path}"
-          rclone copy -L --progress ${tmp_dir}/$tmp_file ${storage_server}:${bucket_name}/${partial_path}
-          exitcode=$?
-        fi
-    else
-        if [[ $compression -eq 1 ]] ; then
-          rclone copy  ${tmp_dir}/$tmp_file ${storage_server}:${bucket_name}/${partial_path} > /dev/null
-          exitcode=$?
-        else
-          #echo "rclone copy -L ${file_path} ${storage_server}:${bucket_name}/${partial_path}"
-          rclone copy -L ${file_path} ${storage_server}:${bucket_name}/${partial_path}
-          exitcode=$?
-        fi    
-    fi
-   
-    
-    if [ $exitcode -ne 0 ]; then
+  #upload with rclone
+  if [[ $silent -eq 0 ]] ; then
+     if [[ $compression -eq 1 ]] ; then  
+        rclone copy --progress ${tmp_dir}/$tmp_file ${storage_server}:${bucket_name}/${partial_path}
+        exitcode=$?     
+     else  
+        # echo "rclone copy -L --progress ${tmp_dir}/$tmp_file ${storage_server}:${bucket_name}/${partial_path}"
+        rclone copy -L --progress ${tmp_dir}/$tmp_file ${storage_server}:${bucket_name}/${partial_path}
+        exitcode=$?
+     fi
+  else
+      if [[ $compression -eq 1 ]] ; then
+         rclone copy  ${tmp_dir}/$tmp_file ${storage_server}:${bucket_name}/${partial_path} > /dev/null
+         exitcode=$?
+      else
+         #echo "rclone copy -L ${file_path} ${storage_server}:${bucket_name}/${partial_path}"
+         rclone copy -L ${tmp_dir}/$tmp_file ${storage_server}:${bucket_name}/${partial_path}
+         exitcode=$?
+      fi    
+  fi
+     
+  if [[ $exitcode -ne 0 ]]; then
        echo $(date +"%d.%m.%y %H:%m:%S") $input $tot_size  $exitcode >> ${tmp_dir}/upload.log
        echo ""
        echo "File upload for $infile failed!"
@@ -1155,30 +1137,31 @@ dmku3fKA/wrOpWntUTkkoQvknjZDisdmSwU4oFk/on0=
        ls -l ${tmp_dir}
        rmdir ${tmp_dir}
        exit 1
-    else
-        printf  "%18s %25s %6s %8s %25s\n" "$(date +"%d.%m.%y %H:%m:%S")" $input $num_files $tot_size "${bucket_name}/${partial_path}" >> ${tmp_dir}/upload.log
-    fi
+  else
+       printf  "%18s %25s %6s %8s %25s\n" "$(date +"%d.%m.%y %H:%m:%S")" $input $num_files $tot_size "${bucket_name}/${partial_path}" >> ${tmp_dir}/upload.log
+  fi
 
-    # rclone md5sums can be calculated only for files that are smaller than 5GB
-    if [[ $tmp_size -lt 5000000 ]]
-    then
-       if [[ $silent -eq 0 ]] ; then
-          echo "Confirming upload..."
-       fi
-       #checksums for local and allas files 
-       sum1=$(md5sum ${tmp_dir}/$tmp_file | awk '{print $1}')
-       if [[ $partial_path == "" ]] ; then
-          allas_path="${storage_server}:${bucket_name}/$tmp_file"
-       else
-          allas_path="${storage_server}:${bucket_name}/${partial_path}/$tmp_file"
-       fi
-       allas_path=$(echo "$allas_path" | sed -e s/"\/\/"/"\/"/g)
+   
+  # rclone md5sums can be calculated only for files that are smaller than 5GB
+  if [[ $tmp_size -lt 5000000 ]]
+  then
+     if [[ $silent -eq 0 ]] ; then
+        echo "Confirming upload..."
+     fi
+     #checksums for local and allas files 
+     sum1=$(md5sum ${tmp_dir}/$tmp_file | awk '{print $1}')
+     if [[ $partial_path == "" ]] ; then
+        allas_path="${storage_server}:${bucket_name}/$tmp_file"
+     else
+        allas_path="${storage_server}:${bucket_name}/${partial_path}/$tmp_file"
+     fi
+     allas_path=$(echo "$allas_path" | sed -e s/"\/\/"/"\/"/g)
       
-       sum2=$(rclone md5sum "$allas_path" | awk '{print $1}')
+     sum2=$(rclone md5sum "$allas_path" | awk '{print $1}')
        
-       #check is cheksums match 
-       if [[ "$sum1" != "$sum2" ]]
-       then 
+     #check is cheksums match 
+     if [[ "$sum1" != "$sum2" ]]
+     then 
          echo "Upload of $input was not successfull!"
          echo "Cleaning the failed upload"
          echo "Upload summary:"
@@ -1189,51 +1172,28 @@ dmku3fKA/wrOpWntUTkkoQvknjZDisdmSwU4oFk/on0=
          rm -f ${tmp_dir}/upload.log
          rmdir ${tmp_dir}
          exit 1
-       fi
-       
-    else  
-       if [[ $mode == "swift" ]]; then  
-          #In case of big swift files Check that all segments are found
-          if [[ $partial_path == "" ]] ; then
+     fi
+      
+  else  
+     if [[ $mode == "swift" ]]; then  
+        #In case of big swift files Check that all segments are found
+        if [[ $partial_path == "" ]] ; then
              seg_check=$(check_segment_sizes "${storage_server}" "${bucket_name}" "${tmp_file}")
-          else
+        else
              seg_check=$(check_segment_sizes "${storage_server}" "${bucket_name}" "${partial_path}/${tmp_file}")
+        fi
+        if [[ $seg_check != "OK"  ]];then
+           echo "ERROR"
+           echo "$seg_check"
+           exit 1
+        else
+          if [[ $silent -eq 0 ]] ; then
+           echo "Sum of segment sizes match the object size. OK "
           fi
-          if [[ $seg_check != "OK"  ]];then
-             echo "ERROR"
-             echo "$seg_check"
-             exit 1
-          else
-             if [[ $silent -eq 0 ]] ; then
-                echo "Sum of segment sizes match the object size. OK "
-             fi
-          fi
-        fi     
-    fi
+        fi
+     fi     
+  fi
   
-#  if [ $mode == "s3cmd" ]
-#  then
-#     if [[ $partial_path == "" ]] ; then
-#        s3cmd put ${tmp_dir}/$tmp_file s3://${bucket_name}/$tmp_file
-#     else
-#        s3cmd put ${tmp_dir}/$tmp_file s3://${bucket_name}/${partial_path}/$tmp_file
-#     fi
-#     exitcode=$?
-#     echo $(date +"%d.%m.%y %H:%m:%S") $input $exitcode >> ${tmp_dir}/upload.log
-#     if [ $exitcode -ne 0 ]; then
-#        echo ""
-#        echo "File upload for $infile failed"
-#        echo "Upload summary:"
-#       cat ${tmp_dir}/upload.log
-#        s3cmd rm s3://${bucket_name}/${partial_path}/$tmp_file
-#        rm -f ${tmp_dir}/$tmp_file 
-#        rm -f ${tmp_dir}/*_ameta
-#        rm -f ${tmp_dir}/upload.log
-#        rmdir ${tmp_dir}
-#        exit 1
-#     fi
-#  fi
-
  
   #echo "Remopving temporary file"
   rm -f  ${tmp_dir}/$tmp_file
@@ -1263,13 +1223,6 @@ dmku3fKA/wrOpWntUTkkoQvknjZDisdmSwU4oFk/on0=
              rclone copy -L ${tmp_dir}/${tmp_file}_ameta ${storage_server}:${bucket_name}/${partial_path} > /dev/null
          fi 
      fi
-#     if [ $mode == "s3cmd" ]; then
-#"         if [[ $partial_path == "" ]] ; then
-#            s3cmd put -F ${tmp_dir}/${tmp_file}_ameta s3://${bucket_name}/${tmp_file}_ameta
-#         else
-#            s3cmd put -F ${tmp_dir}/${tmp_file}_ameta s3://${bucket_name}/${partial_path}/${tmp_file}_ameta
-#         fi
-#     fi
   fi   
   rm -f ${tmp_dir}/${tmp_file}_ameta
 
@@ -1306,9 +1259,9 @@ if [[ $silent -eq 0 ]] ; then
   echo OK
 fi
 rm -f .sdx_key_tmp_$$
-#rm -f ${tmp_dir}/tar_list
-#rm -f ${tmp_dir}/upload.log 
-#rmdir  ${tmp_dir}
+rm -f ${tmp_dir}/tar_list
+rm -f ${tmp_dir}/upload.log 
+rmdir  ${tmp_dir}
 end_time=$(date +%s)
 (( kesto = end_time - start_time ))
 (( nopeus = cumulative_size / kesto ))
