segment size summing based check disabled as it is not compatible with rclone 1.71

diff --git a/a-put b/a-put
--- a/a-put
+++ b/a-put
@@ -1255,24 +1255,27 @@ dmku3fKA/wrOpWntUTkkoQvknjZDisdmSwU4oFk/on0=
          exit 1
      fi
       
-  else  
-     if [[ $mode == "swift" ]]; then  
-        #In case of big swift files Check that all segments are found
-        if [[ $partial_path == "" ]] ; then
-             seg_check=$(check_segment_sizes "${storage_server}" "${bucket_name}" "${tmp_file}")
-        else
-             seg_check=$(check_segment_sizes "${storage_server}" "${bucket_name}" "${partial_path}/${tmp_file}")
-        fi
-        if [[ $seg_check != "OK"  ]];then
-           echo "ERROR"
-           echo "$seg_check"
-           exit 1
-        else
-          if [[ $silent -eq 0 ]] ; then
-           echo "Sum of segment sizes match the object size. OK "
-          fi
-        fi
-     fi     
+  else
+      echo "Checksum comparison skipped for files over 5GB"
+
+     #this check does not work for rclone 1.71
+     #if [[ $mode == "swift" ]]; then  
+     #   #In case of big swift files Check that all segments are found
+     #   if [[ $partial_path == "" ]] ; then
+     #        seg_check=$(check_segment_sizes "${storage_server}" "${bucket_name}" "${tmp_file}")
+     #   else
+     #        seg_check=$(check_segment_sizes "${storage_server}" "${bucket_name}" "${partial_path}/${tmp_file}")
+     #   fi
+     #   if [[ $seg_check != "OK"  ]];then
+     #      echo "ERROR"
+     #      echo "$seg_check"
+     #      exit 1
+     #   else
+     #     if [[ $silent -eq 0 ]] ; then
+     #      echo "Sum of segment sizes match the object size. OK "
+     #     fi
+     #   fi
+     #fi     
   fi
   
  
