size check commented out

diff --git a/a-put b/a-put
--- a/a-put
+++ b/a-put
@@ -1040,19 +1040,19 @@ dmku3fKA/wrOpWntUTkkoQvknjZDisdmSwU4oFk/on0=
      fi
      # Use file size to check that all data is encrypted
      # synchronization needed to get correct size with du
-     sync
+     #sync
      crypt_size=$(du ${tmp_dir}/$tmp_file.tmp | awk '{print $1}')
-     if [[ $crypt_size -lt $tmp_size ]]; then
-        echo "Error: Encryption produced a file that is smaller than the original file!"
-        echo "Chech that crypt4gh works properly and that you have enough free spcace in $tmp_root"
-        exit 1
-     fi
+     #if [[ $crypt_size -lt $tmp_size ]]; then
+     #   echo "Error: Encryption produced a file that is smaller than the original file!"
+     #   echo "Chech that crypt4gh works properly and that you have enough free spcace in $tmp_root"
+     #   exit 1
+     #fi
      if [[ $silent -eq 0 ]] ; then
         echo "Size of the encrypted file is: ${crypt_size}K"
      fi
      rm  ${tmp_dir}/$tmp_file
      mv ${tmp_dir}/${tmp_file}.tmp ${tmp_dir}/$tmp_file
-     tmp_size=$
+     tmp_size=$crypt_size
   fi 
 
 
