Segment size check in a-put and in allas-health-check

diff --git a/a-put b/a-put
--- a/a-put
+++ b/a-put
@@ -49,6 +49,35 @@ echo $path_string
 }
 
 
+check_segment_sizes(){
+  local segment_server="$1"
+  local segments_bucket="${2}_segments"
+  local check_object=$3
+  local segsizes=($(rclone ls ${segment_server}:${segments_bucket}/${check_object}/ | tr "/" " " | awk '{ a = a + $1}END{ print a" "$3 }'))
+
+  if [[ ${#segsizes[@]} -eq 2 ]]; then
+     if [[ ${segsizes[0]} -eq  ${segsizes[1]} ]]; then
+         echo "OK"
+     else
+         if [[ ${segsizes[0]} -lt  ${segsizes[1]} ]]; then
+           local m="ERROR.
+Total size of segments ${segsizes[0]} is less that original file size ${segsizes[1]}.
+Some segments are missing?"
+           echo $m
+         fi
+         if [[ ${segsizes[0]} -gt  ${segsizes[1]} ]]; then
+local m="ERROR. Total size of segments ${segsizes[0]} is more that original file size ${segsizes[1]}.
+Check the segmensts bucket ${segments_bucket} for object ${check_object}."
+           echo $m
+         fi
+
+     fi
+  else
+     #No segements found. Assuming OK
+      echo "OK"
+  fi
+}
+
 
 if [[ $# -lt 1 ]]
 then
@@ -1040,9 +1069,24 @@ do
          rmdir ${tmp_dir}
          exit 1
        fi
-       if [[ $silent -eq 0 ]] ; then
-         echo "$input OK"
+       
+    else    
+       #In case of  files Check that all segments are found
+       if [[ $partial_path == "" ]] ; then
+          seg_check=$(check_segment_sizes "${storage_server}" "${bucket_name}" "${tmp_file}")
+       else
+          seg_check=$(check_segment_sizes "${storage_server}" "${bucket_name}" "${partial_path}/${tmp_file}")
        fi
+       if [[ $seg_check != "OK"  ]];then
+          echo "ERROR"
+          echo "$seg_check"
+          exit 1
+       else
+          if [[ $silent -eq 0 ]] ; then
+            echo "Sum of segment sizes match the object size. OK "
+          fi
+       fi
+     
     fi
   fi
   if [ $mode == "s3cmd" ]
