local directory checking added to a_get. Bucket and object parsing in a_lits.

diff --git a/a_get b/a_get
--- a/a_get
+++ b/a_get
@@ -39,7 +39,7 @@ do
                   shift
                 ;;
              '--target_file' | '-t' )
-                  target_name=$(basenamme $2)
+                  target_name=$(basename $2)
                   if [[ $(dirname $2) != "." ]]; then
                      target_dir=$(dirname $2)
                      new_target=(1)
@@ -212,7 +212,7 @@ if [ $check_os -ne 1 ]; then
   fi
   exit 1
 else
-  echo object_with_bucket
+  #echo object_with_bucket
   object_with_bucket=(1)
 fi
 
@@ -313,17 +313,38 @@ if [[ $target_name == "" ]];then
    fi 
 fi
 
-if [[ -e ${target_dir}/${target_name} ]]; then
-   echo "File name:  ${target_dir}.${target_name} already exists!"
-   echo "Please remove $target_name or define a different target directory name with option: --target_dir " 
+#Test if the target file already axists
+#echo "Target: ${target_dir}/${target_name}"
+if [[ ${target_dir} == "" ]]; then
+  if [[ -e ${target_name} ]]; then
+    echo "File name: ${target_name} already exists!"
+    echo "Please remove $target_name or define a different target directory name with option: --target_dir " 
+    exit 1
+  fi
+else
+   if [[ -e ${target_dir}/${target_name} ]]; then
+      echo "File name:  ${target_dir}/${target_name} already exists!"
+      echo "Please remove ${target_dir}/$target_name or define a different target directory name with option: --target_dir " 
    exit 1
+   fi
 fi
   
 
 echo "Starting to copy data from $storage_server..."
+
+
 if [[ $is_tar_file -eq 1 ]]; then
+     #Processing of a tar/directory
      if [[ $new_target -eq 1 ]];then
-       mkdir -p $target_dir
+       if [[ -e $target_dir ]]; then
+          check_dir=$(file -b $target_dir)
+       else
+          mkdir -p $target_dir
+       fi
+       if [[ $(file -b $target_dir) != "directory" ]]; then
+            echo "Unable to create directory: $target_dir"
+            exit 1
+       fi
        cd $target_dir
      fi
      rclone cat ${storage_server}:/$object_name | zstdmt -d | tar -x -o $file_name  
@@ -331,8 +352,17 @@ if [[ $is_tar_file -eq 1 ]]; then
        cd -   
      fi
 else
-    if [[ $new_target_dir -eq 1 ]];then
-       mkdir -p $target_dir
+    #processing of a file
+    if [[ $new_target -eq 1 ]];then
+       if [[ -e $target_dir ]]; then
+          check_dir=$(file -b $target_dir)
+       else
+          mkdir -p $target_dir
+       fi
+       if [[ $(file -b $target_dir) != "directory" ]]; then
+            echo "Unable to create diretory: $target_dir"
+            exit 1
+       fi
        cd $target_dir
     fi
     # uncompress if needed
@@ -349,7 +379,11 @@ echo ""
 echo "Object:"
 echo "  $object_name "
 echo "copied and uncompressed from $storage_server into:"
-echo "  $target_name"
+if [[ $target_dir == "" ]]; then
+   echo "  ${target_name}"
+else
+   echo "  ${target_dir}/${target_name}"
+fi
 
 
 exit
