Haka note added to allas_conf

diff --git a/allas_conf b/allas_conf
--- a/allas_conf
+++ b/allas_conf
@@ -531,11 +531,13 @@ for p in json.loads(body).get("projects", []):
    else
       local all_projects=($(openstack project list --my-projects -c Name -f value --os-username $OS_USERNAME))
    fi
-
+   
+   
    case ${#all_projects[@]} in
        0)
            echo "Error: No Allas projects found!" >&2
-           echo "Please check that you typed your password correctly" >&2
+           echo "Please check that you typed your CSC password correctly." >&2
+           echo "Note that you University/Haka or Virtu password can't be used here" >&2
            return 1
            ;;
        1)
