allas-mount project and bucket selectors added

diff --git a/allas-mount b/allas-mount
--- a/allas-mount
+++ b/allas-mount
@@ -101,13 +101,19 @@ You can use optional mount points with option -m (--mountpoint)
    
    allas-mount <bucket_name> -m <dir_name>
 
-To unmount a bucket use option -u:
+To unmount a bucket use option -u or --umount:
 
    allas-mount -u  <dir_name>
 
-Option -l lists the currenly active rclone mount commands, launched by allas-mount.
+Option -l (--list) lists the currenly active rclone mount commands, launched by allas-mount.
 
    allas-mount -l
+
+By default buckets are mounted as read-only directories. With option -w (--write) write permissio is
+added to the mounted bucket. Writing data to allas this way can cause problems isn the cases where the
+same object is modifies by several processes in the same time.
+   
+   allas-mount <bucket_name> -w
 
 EOF
 
@@ -115,6 +121,37 @@ exit 0
 
 fi 
 
+#Check if connection works
+if [[ $mode == "swift" ]]
+then
+  #here we check that rclone is available
+  if [[ $(which rclone 2> /dev/null | wc -l ) -ne 1 ]];then
+      echo ""
+      echo "rclone is not available!"
+      echo "Please install rclone."
+      exit 1
+  fi
+  #connection test
+  test=$(rclone about ${storage_server}: 2> /dev/null | wc -l)
+  #test=$(swift stat 2> /dev/null | grep -c "Account:")
+  if [[ $test -lt 1 ]]
+  then 
+    source $inst_root/allas_conf -f
+    test=$(rclone about ${storage_server}: 2> /dev/null | wc -l)
+    if [[ $test -lt 1 ]]
+    then 
+      echo "No connection to Allas!"
+      echo "Please try setting the the connection again."
+      echo "by running command:"
+      echo ""
+      echo "   source $allas_conf_path"
+      exit 1
+    fi
+  fi 
+fi
+
+
+echo "debug 1"
 
 #Unmounting
 if [[ $task == "unmount" ]]; then
@@ -129,23 +166,6 @@ if [[ $task == "unmount" ]]; then
    kill $rclone_pid
    exit 0
 fi
-
-
-
-
-
-if [[ $bucket_name == "" ]]
-then
-  echo "Available buckets:"
-  a-list
-  echo "Please give the bucket to mount:"
-  read bucket_name 
-fi
-
-if [[ $mount_point == "" ]]; then
-   mount_point=$bucket_name
-fi
-
 
 
 #Configure rclone
@@ -181,41 +201,44 @@ then
      export OS_PROJECT_NAME=$os_project_name
 fi 
 
-#Check if connection works
-if [[ $mode == "swift" ]]
-then
-  #here we check that rclone is available
-  if [[ $(which rclone 2> /dev/null | wc -l ) -ne 1 ]];then
-      echo ""
-      echo "rclone is not available!"
-      echo "Please install rclone."
-      exit 1
-  fi
-  #connection test
-  test=$(swift stat 2> /dev/null | grep -c "Account:")
-  if [[ $test -lt 1 ]]
-  then 
-    echo "No connection to Allas!"
-    echo "Please try setting the the connection again."
-    echo "by running command:"
-    echo ""
-    echo "   source $allas_conf_path"
-    exit 1
-  fi 
-fi
+
 
 #source /appl/opt/allas_conf
 #input=("$1")
+if [[ $bucket_name == "" ]]
+then
+  #echo "rclone lsf ${storage_server}: | grep -v segments | tr -d '/' "
+  #rclone lsf ${storage_server}: | grep -v segments | tr -d "/" |  tr "\n" " "
+  all_buckets=($(rclone lsf ${storage_server}: | grep -v segments | tr -d "/" | tr "\n" " "))
+  echo "Please choose a buket by giving an item number form the list above: "
+  case ${#all_buckets[@]} in
+    0)
+           echo "Error: No buckets found!" >&2
+           exit 1
+    ;;
+    *)
+    select bucket_name in "${all_buckets[@]}" "abort allas-mount"; 
+    do
+      [[ -n "$bucket_name" ]] && break
+    done
+    if [[ "$bucket_name" == "abort allas-mount" ]]; then
+      exit 0 
+    fi
+    ;;
+  esac  
+fi
 
+if [[ $mount_point == "" ]]; then
+   mount_point=$bucket_name
+fi
 #check that bucket exists
 
 
 check_bucket=$(rclone lsd ${storage_server}:$bucket_name 2>&1 | wc -l)
-if [ $check_bucket -eq 0 ]; then
+if [[ $check_bucket -eq 0 ]]; then
   echo "Bucket name: $bucket_name not found in $storage_server."
   echo ""
-  echo "Exucute command:  a-list "
-  echo "to see the available buckets"
+  exit 1
 fi
 
 #Test if the target file already axists
