allas-backup: new restore versions added

diff --git a/allas-backup b/allas-backup
--- a/allas-backup
+++ b/allas-backup
@@ -19,7 +19,9 @@ help=0
 mode="swift"
 packsize=64
 
-if [[ $1 == "add" || $1 == "list" ||  $1 == "restore" || $1 == "delete" || $1 == "find" || $1 == "files" || $1 == "dump" || $1 == "unlock" ]]
+
+
+if [[ $1 == "add" || $1 == "list" ||  $1 == "restore" || $1 == "restore-overwrite" || $1 == "restore-newer" || $1 == "find" || $1 == "files" || $1 == "dump" || $1 == "unlock" ]]
 then
    task="$1"
    shift
@@ -157,9 +159,21 @@ allas-backup can be used for following five operations:
 
   allas-backup find <query>          Find snapshots that contain file or directory that match the given query term.
 
-  allas-backup restore <snapshot_id> Retrieves the data of the given snapshot to the local environment. By default 
-                                 the stored data is restored to the local directory. Other locations can be 
-                                 defined with -target option.
+  allas-backup restore <snapshot_id> Retrieves the data of the given snapshot to the local environment. 
+                                     By default the stored data is restored to the local directory. Other locations can be 
+                                     defined with -target option.
+                                     Existing local files will not be overwritten. Only missing files will be retrieved.
+
+  allas-backup restore-overwrite <snapshot_id> Retrieves the data of the given snapshot to the local environment. 
+                                     By default the stored data is restored to the local directory. Other locations can be 
+                                     defined with -target option.
+                                     Existing local files will be overwritten.    
+
+  allas-backup restore-newer <snapshot_id> Retrieves the data of the given snapshot to the local environment. 
+                                     By default the stored data is restored to the local directory. Other locations can be 
+                                     defined with -target option.
+                                     Existing local files will be overwritten only if the file in the snapshot has a newer modification time.                               
+
 
   allas-backup delete <snapshot_id>  Deletes a snapshot from the backup repository.
 
@@ -184,6 +198,7 @@ fi
 
 # Check connecting in case of swift
 if [[ $mode == "swift" ]]; then 
+   echo "Checking connection to Allas."
    # update connection is allas-conf -k is in use      
    if [[ -n "$OS_PASSWORD" ]]; then   
       echo "Updating token"
@@ -238,6 +253,10 @@ then
    restic init --repo $repository -p $HOME/.backup_passwd_${project_label} 
 fi 
 
+echo ""
+echo "Using backup repository: $repository"
+echo "" 
+
 
 if [[ $task == "add" ]]
 then
@@ -291,9 +310,52 @@ then
      echo ""
      exit 1
   fi
-  restic restore --repo $repository -p $HOME/.backup_passwd_${project_label} $input --target $target $options
+  if [[ $target == "./" ]]; then
+     echo "Restoring snapshot $input to current directory"
+  else
+     echo "Restoring snapshot $input to directory: $target"
+  fi
+  echo "Only missing files will be downloaded. Existing local files will not be overwritten."
+  echo ""
+   
+  restic restore --repo $repository --overwrite never -p $HOME/.backup_passwd_${project_label} $input --target $target $options
+fi
+
+if [[ $task == "restore-overwrite" ]]
+then
+  if [[ $input == "" ]] ; then
+     echo "No snapshot name defined. Please give the snapshot name as a command line argument."
+     echo ""
+     exit 1
+  fi
+  if [[ $target == "./" ]]; then
+     echo "Restoring snapshot $input to current directory."
+  else
+     echo "Restoring snapshot $input to directory: $target"
+  fi
+  echo "All files from the snapshot will be downloaded. Existing local files will be overwritten."
+  echo ""
+  restic restore --repo $repository --overwrite always -p $HOME/.backup_passwd_${project_label} $input --target $target $options
 fi
  
+if [[ $task == "restore-newer" ]]
+then
+  if [[ $input == "" ]] ; then
+     echo "No snapshot name defined. Please give the snapshot name as a command line argument."
+     echo ""
+     exit 1
+  fi
+    if [[ $target == "./" ]]; then
+     echo "Restoring snapshot $input to current directory."
+  else
+     echo "Restoring snapshot $input to directory: $target"
+  fi
+  echo "Existing local files will be overwritten only if the time stamp in the snapshot is newer than in the local file."
+  echo ""
+
+  restic restore --repo $repository --overwrite if-newer -p $HOME/.backup_passwd_${project_label} $input --target $target $options
+fi
+
 
 if [[ $task == "delete" ]]
 then
