allas-backup fix

diff --git a/allas-backup b/allas-backup
--- a/allas-backup
+++ b/allas-backup
@@ -253,32 +253,28 @@ fi
 
 ### Settings in case of S3
 if [[ $mode == "s3cmd" ]]; then  
-  if [[ -e  $HOME/.aws/credentials ]]; then
-     export AWS_DEFAULT_REGION=""
-     export $(grep AWS_ACCESS_KEY_ID  $HOME/.aws/credentials)
-     export $(grep AWS_SECRET_ACCESS_KEY $HOME/.aws/credentials)
+  ### Settings for S3  
+  if [[ -e  $HOME/.config/rclone/rclone.conf ]]; then
+    accesskey=$(awk '{ if ( NF == 1 ) ep = $1}{ if ( $1 == "access_key_id" ) print ep" "$3 }' $HOME/.config/rclone/rclone.conf | tr -d "[","]" | awk  '{ if ( $1 == "s3allas" ) print $2 }')
+    secretaccesskey=$(awk '{ if ( NF == 1 ) ep = $1}{ if ( $1 == "secret_access_key" ) print ep" "$3 }' $HOME/.config/rclone/rclone.conf | tr -d "[","]" | awk  '{ if ( $1 == "s3allas" ) print $2 }')
+    os_project_name=$(awk '{ if ( NF == 1 ) ep = $1}{ if ( $1 == "access_key_id" ) print ep" "$3 }' $HOME/.config/rclone/rclone.conf | tr -d "[","]" | awk  '{ if ( $2 == "'$accesskey'" ) print $1 }' | grep "lumi-" | grep "private" | awk -F "-" '{print $2}')
+    export AWS_DEFAULT_REGION=""
+    export AWS_ACCESS_KEY_ID="$accesskey"
+    export AWS_SECRET_ACCESS_KEY="$secretaccesskey"
   else
-     echo "Unable to find S3 credentials for Allas."
-     exit 1
+    echo "Unable to find S3 credentials for Allas."
+    exit 1
   fi
-  if [[ -z "${OS_PROJECT_NAME}" ]]; then
-     
-      #check what project s3allas uses
-      accesskey=$(awk '{ if ( NF == 1 ) ep = $1}{ if ( $1 == "access_key_id" ) print ep" "$3 }' $HOME/.config/rclone/rclone.conf | tr -d "[","]" | awk  '{ if ( $1 == "s3allas" ) print $2 }')
-      if [[ "$accesskey" != "$AWS_ACCESS_KEY_ID" ]]; then
-         echo "aws and rclone s3allas: end point do not refer to same project. Exiting."
-         exit 1
-      fi
-      #echo accesskey: $accesskey
-      os_project_name=$(awk '{ if ( NF == 1 ) ep = $1}{ if ( $1 == "access_key_id" ) print ep" "$3 }' $HOME/.config/rclone/rclone.conf | tr -d "[","]" | awk  '{ if ( $2 == "'$accesskey'" ) print $1 }' | grep "s3allas-"  | awk -F "-" '{print $2}')
-      if [[ "$project_label" == "" ]]; then
-          project_label=$(echo ${os_project_name} | sed -e s/"project_"/""/g)
-      fi
-      if [[ "$project_label" == "" ]]; then  
+  
+  if [[ "$project_label" == "" ]]; then
+     project_label=$(echo ${os_project_name} | sed -e s/"project_"/""/g)
+  fi
+      
+   if [[ "$project_label" == "" ]]; then  
          echo "Unable to define default project name."
          exit 1
-      fi
-  fi    
+   fi
+   
   bucket_name="${project_label}-s3backup"
   repository="s3:a3s.fi/${bucket_name}"  
   check_repo=$(rclone ls s3allas:${bucket_name}/backup/config | wc -l)
