new allas_conf, a-get fix, README update

diff --git a/allas_conf b/allas_conf
--- a/allas_conf
+++ b/allas_conf
@@ -1,69 +1,6 @@
-#!/bin/bash 
+#!/bin/bash
 
-# This is a help tool to set up connections to the Allas storage service
-# https://a3s.fi
-
-
-## 1. Print help if asked.
-##
-if [[ $1 == "-h" ||  $1 == "-help" ||  $1 == "--help" ]]
-then
-  echo "This script sets up the swift and/or s3cmd environment so that you can access Allas storage service. "
-  echo "The name of the Allas project to be used can be defined as a command line argument."
-  echo ""
-  echo "   source allas_conf <proj_name>"
-  echo ""
-  echo "If the project name is not defined, the available project names are listed and"
-  echo "you are asked to define the project name based on the list."
-  echo ""
-  echo "The program asks your CSC password before starting the configuration process."
-  echo ""
-  echo "By default, this tool sets up access tokens that are used by swift and rclone connections"
-  echo " "
-  echo "Definition:"
-  echo ""
-  echo "--mode s3cmd" 
-  echo ""
-  echo "will initiate s3cmd configuration in stead of swift configuration."
-  echo ""
-  echo "Definition:"
-  echo ""
-  echo "--mode both" 
-  echo ""
-  echo "will initiate both swift and s3cmd configuration."
-  echo ""
-  echo "During s3cmd configuration, you will be asked to confirm several values and settings"
-  echo "You should accept the default values in all exept the last setep."
-  echo " WHEN THE TOOL ASKS:"
-  echo '     Save settings? [y/N]' 
-  echo "YOU SHOULD ANSVER: y"
-  echo " "
-  echo "Other options:"
-  echo "  --user <username>    Define usename to be used for authentication to the storage server."
-  echo "                      If this option is not defined, current username will be used."
-  echo ""
-  echo "  --keeppasswd         Don't reset the OS_PASSWORD environment variable once the configuration"
-  echo "                      is done. This can be useful if you use this tool in scripts that need to"
-  echo "                      switch between projects."
-  echo ""
-  echo "  --silent             Less output"
-              
-  return
-fi
-
-## 2. Define variables
-##
-#interenal variables
-storage_service=("allas")
-show_keys=(0)
-use_swift=(1)
-use_s3cmd=(0)
-keep_password=(0)
-silent_mode=(0)
-active_mode=(0)
-force=(0)
-#default evironmnet variables
-export OS_PROJECT_NAME="" 
+export OS_PROJECT_NAME=""
 export OS_PROJECT_ID=""
 export OS_STORAGE_URL=""
 export OS_AUTH_TOKEN=""
@@ -74,292 +11,257 @@ export OS_REGION_NAME="regionOne"
 export OS_INTERFACE=public
 export OS_IDENTITY_API_VERSION=3
 
-## 3. Go through the command line arguments
-##
-while [[ $# -ge 1 ]]
-do
-  case "$1" in
-             '-m' | '--mode')
-             if [ $2 == "s3cmd" ]; then
-                use_swift=(0)
-                use_s3cmd=(1)
-             fi 
-             if [ $2 == "both" ]; then             
-                use_swift=(1)
-                use_s3cmd=(1)
-             fi             
-             shift
-             shift
-             ;;
-             '-w' | '--show_keys')
-              show_keys=(1)
-              shift
-             ;;
-             '-u' | '--user')
-             export OS_USERNAME=$2
-             shift
-             shift
-             ;;
-             '-k' | '--keeppasswd')
-             keep_password=(1)
-             shift
-             ;;
-             '-s'| '--silent')
-             silent_mode=(1)
-             shift
-             ;;
-             '-a'| '--active-token')
-             active_mode=(1)
-             shift
-             ;;
-             '-f'| '--force')
-             force=(1)
-             shift
-             ;;
-             *)
-             export OS_PROJECT_NAME=$1 
-             shift                       # No more switches
-             ;;
+
+
+allas_conf_scope () {
+
+local usage="
+
+Usage: source allas_conf [OPTIONS] [PROJECT]
+
+    This script sets up the environment variables and the configuration
+    files for accessing Allas storage service https://a3s.fi using swift
+    (default) and/or s3cmd APIs.
+
+    The program asks your CSC password before starting the configuration
+    process.
+
+    If the project name is not given as PROJECT argument, the available
+    project names are listed and you are asked to choose one.
+
+    By default, this tool sets up access tokens that are used by swift and
+    rclone connections.
+
+
+    OPTIONS
+    -------
+
+        --mode s3cmd         Configure s3cmd API (default: swift)
+
+        --mode both          Configure both swift and s3cmd APIs
+
+        --user USER          Storage server username (default: $USER)
+
+        --keeppasswd         Keep OS_PASSWORD environment variable once the
+                             configuration is done. This can be useful if you
+                             use this tool in scripts that need to
+                             switch between projects.
+
+        --chuncksize SIZE    s3cmd chunk size, 5-5000, Files larger than
+                             SIZE, in MB, are automatically uploaded
+                             multithread-multipart  (default: 5000)
+
+        --silent             Less output
+
+
+    DEPENDENCIES
+    ------------
+
+    This script uses openstack and swift/s3cmd utilities, which in
+    puhti.csc.fi are available using
+
+        module load allas
+
+    On other machines these need to be installed separately, see README.md
+    for example.
+"
+
+local storage_service=("allas")
+local show_keys=false
+local keep_password=false
+local silent_mode=false
+local active_mode=false
+local echop=echo
+local chunk_size=5000
+local rconf=$HOME/.config/rclone/rclone.conf
+local mode=swift
+local force=false
+
+# Process command line arguments
+
+while [[ $# -ge 1 ]]; do
+    case "$1" in
+        '-h'|'-help'|'--help')  echo "$usage";           return 0;;
+        '-m'|'--mode')          mode="$2";               shift 2;;
+        '-w'|'--show_keys')     show_keys=true;          shift;;
+        '-u'|'--user')          export OS_USERNAME="$2"; shift 2;;
+        '-k'|'--keeppasswd')    keep_password=true;      shift;;
+        '-s'|'--silent')        echop=:;                 shift;;
+        '-c'|'--chunksize')     chunk_size="$2";         shift 2;;
+        '-a'|'--active-token')  active_mode=true;        shift;;
+        '-f'|'--force' )        force=true;              shift;;
+        *) export OS_PROJECT_NAME="$1";                  shift;;
     esac
 done
 
-if [ "$0" != "bash" -a "$0" != "-bash" -a "$0" != "/bin/bash" -a "$force" -eq 0 ]; then
-   echo $0
-   echo "allas_conf should not be executed directly"
-   echo "Use sourcing in stead: "
-   echo "   source allas_conf -u CSC-usrname allas_project"
-   exit 1
+# check if this is executed as sourced command
+if [ "$0" != "bash" -a "$0" != "-bash" -a "$0" != "/bin/bash" -a "$force" == "false" ]; then
+    echo "Error: allas_conf should not be executed directly. $usage" >&2
+    exit 1
+fi
+
+case "$mode" in
+    's3cmd')
+        local use_swift=false
+        local use_s3cmd=true
+        ;;
+    'both')
+        local use_swift=true
+        local use_s3cmd=true
+        ;;
+     'swift')
+        local use_swift=true
+        local use_s3cmd=false
+        ;;  
+    *)
+        echo "Error: Wrong argument to '--mode' option $usage" >&2
+        return 1
+        ;;
+esac
+
+if [[ "$chunk_size" -lt 5 || "$chunk_size" -gt 5000 || \
+          ! "$chunk_size" =~ ^[0-9]+$ ]]; then
+    echo "\nError: Invalid chuck size. $usage" >&2
+    return 1
+fi
+
+if ! $keep_password; then
+    trap 'unset OS_PASSWORD; trap - RETURN EXIT SIGINT' RETURN EXIT SIGINT
 fi
 
 
-## 3. Check  that swift and/or s3cmd are available
-##
+# Check availability of command line tools
 
-
-if [[ $use_s3cmd -eq 1 ]]
-then
-   if [[ $(which s3cmd 2>/dev/null | wc -c) -eq 0 ]]
-   then 
-      echo ""
-      echo "s3cmd command not found!"
-      return
-   fi
+if [ -z "$OS_PROJECT_NAME" ] && ! command -v openstack >/dev/null 2>&1; then
+    echo -e "\nError: openstack command not found!" >&2
+    return 1
 fi
 
-if [[ $use_swift -eq 1 ]]
-then
-   if [[ $(which swift 2>/dev/null | wc -c) -eq 0 ]]
-   then 
-      echo ""
-      echo "swift command not found!"
-      return
-   fi
+if $use_s3cmd && ! command -v s3cmd >/dev/null 2>&1; then
+        echo -e "\nError: s3cmd command not found!" >&2
+        return 1
 fi
 
-## 4. Ask for CSC password
-##
-# With Keystone you pass the keystone password.
-if [ -z "$OS_PASSWORD" ]; then 
+if $use_swift && ! command -v swift >/dev/null 2>&1; then
+    echo -e "\nError: swift command not found!" >&2
+    return 1
+fi
+
+if ! command -v rclone >/dev/null 2>&1; then
+    echo "NOTE: rclone command was not found."
+fi
+if ! command -v restic >/dev/null 2>&1; then
+    echo "NOTE: restic command was not found."
+fi
+
+
+# Ask for CSC password
+
+if [ -z "$OS_PASSWORD" ]; then
    echo "Please enter CSC password for account ${OS_USERNAME}: "
-   read -sr OS_PASSWORD_INPUT
-   export OS_PASSWORD=$OS_PASSWORD_INPUT
-else 
-   export OS_PASSWORD_INPUT=${OS_PASSWORD}
+   read -sr OS_PASSWORD
+   export OS_PASSWORD
 fi
 
 
-## 5. Check if OpenStack is available and connection to OS_AUTH_URL accessible 
-##    Assign the project to be used.
-##
+# Assign the project to be used.
+
 if [ -z "$OS_PROJECT_NAME" ]; then
-   
    echo "Checking projects available for your account."
    echo "Please wait."
-  
-   if [[ $(which openstack 2>/dev/null | wc -c) -eq 0 ]]
-   then 
-        echo "openstack command not found!"
-        echo ""
-        echo "Try executing setup command:"
-        echo ""
-        echo "  module load allas "
-        echo ""
-        echo "To make openstack available"
-        echo ""
-        echo "openstack is not needed for Swift based connections,"
-        echo "if you define the project name as an argument for allas_conf "
-        echo ""
-        echo "   source allas_conf allas_project_name"
-        echo ""
-        echo "You can use https://my.csc.fi to check the project names"
-        return
-   fi
 
-   all_projects=$(openstack project list --my-projects -c Name -f value --os-username $OS_USERNAME)
-   echo $all_projetcs
-   num_projects=$(echo $all_projects | wc -w )
-   if [[ $num_projects -lt 1 ]]
-   then
-      echo ""
-      echo "No Allas projects found!"
-      echo "Please check that you typed your password correctly"
-      unset OS_PASSWORD
-      return
-   fi
+   local all_projects=(
+       $(openstack project list \
+                   --my-projects -c Name -f value --os-username $OS_USERNAME))
 
-   # If user has just one project, use it
-   if [[ $OS_PROJECT_NAME == "" && $num_projects -eq 1 ]]
-   then 
-      export OS_PROJECT_NAME=$all_projects
-      echo "Configuration will be done for project: $OS_PROJECT_NAME"
-    fi
-
-   if [[ $OS_PROJECT_NAME == "" ]]
-   then 
-     echo "You have access to following Allas projects:"
-     echo ""
-     echo -e  "Project ID        Description"
-     echo "--------------------------------------------"
-     
-     # If saldo command is available, use it to obtain project descriptions"
-     if [[ $(which saldo 2>/dev/null | wc -c) -ne 0 ]]
-     then 
-        for proj in $all_projects 
-        do
-          projnum=$( echo $proj | sed -e s/"project_"/""/g | sed -e s/"Project_"/""/g )
-          nimi=$(saldo -p $projnum | grep "^Project"| cut -c16-150 )
-          echo "$proj $nimi"
-        done
-     else
-        echo $all_projects | tr " " "\n"
-     fi 
-     echo ""
-     echo "Please define the Project ID of the project to be used:"
-     read OS_PROJECT_NAME
-     export OS_PROJECT_NAME=$(echo $OS_PROJECT_NAME | awk '{print $1}')
-   fi  
+   case ${#all_projects[@]} in
+       0)
+           echo "Error: No Allas projects found!" >&2
+           echo "Please check that you typed your password correctly" >&2
+           return 1
+           ;;
+       1)
+           export OS_PROJECT_NAME=${all_projects[0]}
+           echo "Configuration will be done for project: $OS_PROJECT_NAME"
+           ;;
+       *)
+           PS3="Please choose a project: "
+           local project
+           select project in "${all_projects[@]}" "abort allas_conf"; do
+               [[ -n "$project" ]] && break
+           done
+	   if [[ "$project" == "abort allas_conf" ]]; then
+	       return 1
+	   fi
+           export OS_PROJECT_NAME=$project
+           ;;
+   esac
 fi
 
-## 6.Define authentication
-##
 
-##############################################
-# swift authentication is the default option
-##############################################
+# 6.1 swift configuration
 
-## 6.1 Authenticate with swift
-##
-if [ $use_swift -eq 1 ]; then
-    # authenticate and save token to environment variable
-    source <(swift auth) 
- 
-    if [[ $(grep -c "\[$storage_service\]"  $HOME/.config/rclone/rclone.conf 2> /dev/null ) -lt 1 ]]
-    then
-       mkdir -p  $HOME/.config/rclone/
-       echo '['"$storage_service"']' >> $HOME/.config/rclone/rclone.conf 
-       echo 'type = swift' >>  $HOME/.config/rclone/rclone.conf 
-       echo 'env_auth = true'  >>  $HOME/.config/rclone/rclone.conf
-       if [ $silent_mode -ne 1 ]; then
-           echo ""
-           echo "$storage_service service added to the rclone configuration file."
-       fi
+if $use_swift; then
+
+    #
+    if command -v openstack >/dev/null 2>&1; then
+       export OS_PROJECT_ID=$(openstack project show -f value -c id $OS_PROJECT_NAME)      
     fi
-       
-    os_test=("${OS_AUTH_TOKEN}x")
-    if [  $os_test == "x" ] ; then 
-       echo ""
-       echo "Swift authentication failed!"
-       echo "Are you sure that the password and project ID are valid?"
-       echo "Please try again."
-       unset OS_PASSWORD
-       return 
-    else 
-       if [ $silent_mode -ne 1 ]; then
-          echo "$storage_service connection configured successfully."
-          echo " "
-          #echo "OS_AUTH_TOKEN = $OS_AUTH_TOKEN"
-          #echo "OS_STORAGE_URL = $OS_STORAGE_URL"
-       fi
-       if [ $active_mode -eq 1 ];then
-          export ACTIVE_TOKEN=$(launch_atoken $$)
-          if [ $silent_mode -ne 1 ]; then
-             echo "ACTIVE_TOKEN launched"
-          fi
-      fi
+
+
+    # authenticates and save token to environment variable
+    eval "$(swift auth)"
+
+    if [[ $(grep -c "\[${storage_service}\]" $rconf 2> /dev/null) -lt 1 ]]; then
+        mkdir -p  ${rconf%/*}
+        printf "%s\n" >> $rconf \
+            "[${storage_service}]" \
+	    "type = swift" \
+	    "env_auth = true"
+        $echop "$storage_service service added to '$rconf'."
+    fi
+
+    if [ -z "${OS_AUTH_TOKEN}" ] ; then
+        echo "Error: Swift authentication failed!" >&2
+        echo "Are you sure that the password and project ID are valid?" >&2
+        echo "Please try again."  >&2
+        return 1
+    else
+        $echop "$storage_service connection configured successfully."
+        if $active_mode; then
+            export ACTIVE_TOKEN=$(launch_atoken $$)
+            $echop "ACTIVE_TOKEN launched"
+        fi
     fi
 fi
 
 
-## 6.2 Authenticate with s3cmd
-##
+# 6.2 s3cmd configuration
 
-#########################
-# s3cmd configuration
-#########################
-if [ $use_s3cmd -eq 1 ]; then
-   
-   if [[ $(which openstack 2>/dev/null | wc -c) -eq 0 ]]
-   then 
-        echo "openstack command not found!"
-        echo ""
-        echo "Try executing setup command:"
-        echo ""
-        echo "  module load allas "
-        echo ""
-        echo "To make openstack available"
-        return
-   fi
+if $use_s3cmd; then
 
-   export OS_PROJECT_ID=$(openstack project show -f value -c id $OS_PROJECT_NAME)
-   openstack project show $OS_PROJECT_NAME
+    export OS_PROJECT_ID=$(openstack project show -f value -c id $OS_PROJECT_NAME)
+    openstack project show $OS_PROJECT_NAME
 
-   ACCESS_KEY=$(openstack ec2 credentials list -f value | grep $OS_PROJECT_ID | tail -1 | awk '{print $1}')
-   if [[ $ACCESS_KEY == "" ]]
-   then
+    local ACCESS_KEY=$(
+        openstack ec2 credentials list -f value | grep $OS_PROJECT_ID | tail -1 | awk '{print $1}')
+   if [ -z "$ACCESS_KEY" ]; then
      openstack ec2 credentials create
-     ACCESS_KEY=$(openstack ec2 credentials list -f value | grep $OS_PROJECT_ID | tail -1 | awk '{print $1}')
+     local ACCESS_KEY=$(openstack ec2 credentials list -f value | grep $OS_PROJECT_ID | tail -1 | awk '{print $1}')
    fi
 
-   SECRET_KEY=$(openstack ec2 credentials list -f value | grep $OS_PROJECT_ID | tail -1 | awk '{print $2}')
+   local SECRET_KEY=$(openstack ec2 credentials list -f value | grep $OS_PROJECT_ID | tail -1 | awk '{print $2}')
 
-    echo "Please define the chunk size for a multipart upload."
-    echo "Files bigger than SIZE are automatically uploaded as multithreaded-"
-    echo "multipart, smaller files are uploaded using the" 
-    echo "traditional method. SIZE is in Mega-Bytes, default"
-    echo "chunk size is 500MB, minimum allowed chunk size is 5MB,"
-    echo "maximum is 5000MB."
-    echo
-    echo "chunk size[5000]:"
-    read chunk_size
-    if [[ $chunk_size == "" ]]
-    then
-        chunk_size=5000
-    fi
-    if [[ $chunk_size -gt 5000 ]]
-    then
-        echo "ERROR: Chunk size exceeds the maximum 5000 MB"
-        return
-   fi
-   if [[ $chunk_size -lt 5 ]]
-   then
-      echo "ERROR: Chunk size can't be less than 5 MB"
-      return
-   fi
-
-   echo "---------------------------------------------------------------"
+   echo -e "\n\n\n\n\n\n\n\n\n\ny\n" | \
+       s3cmd --configure \
+             --access_key=$ACCESS_KEY \
+             --secret_key=$SECRET_KEY \
+             --host=a3s.fi \
+             --signature-v2 \
+             --multipart-chunk-size-mb=$chunk_size \
+             --host-bucket='%(bucket)s.a3s.fi' -c $HOME/.s3cfg
    echo ""
-   echo "Starting s3cmd configuration"
-   echo ""
-   echo "Accept the default values except in for the last step:"
-   echo " WHEN THE TOOL ASKS:"
-   echo '     Save settings? [y/N]' 
-   echo "YOU SHOULD ANSVER: y"
-   echo ""
-   echo "---------------------------------------------------------------"
-
- s3cmd --configure --access_key=$ACCESS_KEY --secret_key=$SECRET_KEY \
- --host=a3s.fi --signature-v2 --multipart-chunk-size-mb=$chunk_size \
- --host-bucket='%(bucket)s.a3s.fi' -c $HOME/.s3cfg 
+   echo "s3mcd configuration ready."
 
 
  #  s3cmd --configure --access_key=$ACCESS_KEY --secret_key=$SECRET_KEY \
@@ -376,22 +278,16 @@ echo "user=$OS_USERNAME" >>  $HOME/.allas_default
 # unset variables unnecessary for token access or user/project info for the user
 unset OS_AUTH_URL
 unset OS_USER_DOMAIN_NAME
-unset OS_PASSWORD
-if [ $keep_password -eq 1 ];then    
-  export OS_PASSWORD="$OS_PASSWORD_INPUT"
+if ! $keep_password; then
+  unset OS_PASSWORD
 fi
-
-unset OS_PASSWORD_INPUT
 unset OS_REGION_NAME
 unset OS_INTERFACE
 unset OS_IDENTITY_API_VERSION
 
-#check if rclone and restic are available
-if [[ $(which rclone 2>/dev/null | wc -c) -eq 0 ]]
-then 
-   echo "NOTE: rclone command was not found."
-fi
-if [[ $(which restic 2>/dev/null | wc -c) -eq 0 ]]
-then 
-   echo "NOTE: restic command was not found."
-fi
+
+
+}
+
+allas_conf_scope "$@"
+unset -f allas_conf_scope
