a- to lo-

diff --git a/lo-stream b/lo-stream
--- a/lo-stream
+++ b/lo-stream
@@ -95,10 +95,10 @@ done
 
 if [ $print_help -eq 1 ]; then
 cat <<EOF
-This tool is used to stream data, that has been uploaded to LUMI-O service using the a-put command.
+This tool is used to stream data, that has been uploaded to LUMI-O service using the lo-put command.
 The basic syntax of the command is:
 
-   a-stream object_name
+   lo-stream object_name
 
 By default the object is retrieved and uncompressed 
 
@@ -112,7 +112,7 @@ Options:
 
 --s3cmd                       Use S3 protocol and s3cmd command for data retrieval instead of Swift protocol and rclone.
 
-Related commands: a-put, a-find, a-info, a-delete
+Related commands: lo-put, lo-find, lo-info, lo-delete
 
 EOF
 
@@ -212,13 +212,13 @@ else
   #check if object exists
   bucket_found=$(rclone ls ${storage_server}:/$object_name 2> /dev/null | wc -l)
   if [ $bucket_found -ne 1 ]; then
-     a-find 
+     lo-find 
 
      echo "" >&2
      echo "Object $object_name was not found" >&2
      echo "" >&2
      echo "You can list all the available objects with command:" >&2
-     echo "   a-find" >&2
+     echo "   lo-find" >&2
   fi
 fi 
    
@@ -302,7 +302,7 @@ echo "Starting to stream data from $storage_server..." >&2
 
 
 if [[ $is_tar_file -eq 1 ]]; then
-  echo "Tar files can't be streamed with a-stream" >&2
+  echo "Tar files can't be streamed with lo-stream" >&2
   exit
 fi
      
diff --git a/lumio-share-bucket b/lumio-share-bucket
--- a/lumio-share-bucket
+++ b/lumio-share-bucket
@@ -1,4 +1,4 @@
-#!/bin/bash 
+#!/bin/bash
 
 
 #default user
@@ -23,11 +23,11 @@ mode=("swift")
 #Process command line
 while [[ $# -ge 1 ]]
 do
-  case "$1" in           
+  case "$1" in
              '--bucket' | '-b' )
-                  bucket=($2)             
+                  bucket=($2)
                   shift
-                  shift 
+                  shift
               ;;
               '-i' | '--id' )
                   project_id="$2"
@@ -49,32 +49,32 @@ do
                 ;;
     esac
 done
-   
+
 
 
 if [ $print_help -eq 1 ]; then
 cat <<EOF
 
 By default, only project members can read and write the data in a bucket.
-Members of the project can grant read and write access to the bucket and 
-the objects it contains, for other Allas projects or make the bucket publicly
+Members of the project can grant read and write access to the bucket and
+the objects it contains, for other LUMI-O projects or make the bucket publicly
 accessible to the internet.
 
-allas-share-bucket tool gives the specified read and write permissions to
-the bucket defined for both SWIFT and S3 protocols. 
+lumio-share-bucket tool gives the specified read and write permissions to
+the bucket defined for both SWIFT and S3 protocols.
 
-Before running this command you need to setup the allas connection
+Before running this command you need to setup the lumio connection
 with commands:
 
    module load lumio
-   allas-conf --mode both -k 
- 
+   lumio_conf --mode both -k
 
-allas-share-bucket command needs three mandatory arguments:
+
+lumio-share-bucket command needs three mandatory arguments:
 
  -b, --bucket           The bucket to be shared
 
- -p, --project          Name of the project for which 
+ -p, --project          Name of the project for which
                         the access will be granted
 
  -i, --id               ID of the project for which
@@ -82,44 +82,44 @@ allas-share-bucket command needs three mandatory arguments:
 
 Note, that you need to define both the ID and the name of the target project.
 
-For example, to allow members of project: project_2001234 
+For example, to allow members of project: project_2001234
 (id; 3dsd9wdjjd93kdkd9d4r ) to have read-only access to
 bucket: my_data_bucket you can use command:
 
-  a-access -p project_2001234 -i 3dsd9wdjjd93kdkd9d4r -b my_data_bucket
+  lo-access -p project_2001234 -i 3dsd9wdjjd93kdkd9d4r -b my_data_bucket
 
-The access permissions are set similarly to the corresponding _segments 
+The access permissions are set similarly to the corresponding _segments
 bucket too.
 
 Note, that bucket listing tools don't show the bucket names of other projects,
 not even in cases were the project has read and/or write permissions to the bucket.
 
-For example in this case a user, belonging to project project_2001234, 
+For example in this case a user, belonging to project project_2001234,
 don't see the my_data_bucket in the bucket list produced by command:
-  
-  a-list
 
-but the user can still list the contents of this bucket with command: 
+  lo-list
 
-  a-list my_data_bucket
+but the user can still list the contents of this bucket with command:
+
+  lo-list my_data_bucket
 
 
 EOF
 exit 0
-fi 
+fi
 
 #Check that bucket exists
 bnrows=$(swift stat $bucket 2> /dev/null | wc -l )
 if [[ $bnrows -eq 0 ]]; then
-   echo "Bucket $bucket was not found in your current Allas project!"
+   echo "Bucket $bucket was not found in your current LUMI-O project!"
    echo "Trying to create the bucket"
    rclone mkdir $bucket
    bnrows=$(swift stat $bucket 2> /dev/null | wc -l )
    if [[ $bnrows -eq 0 ]]; then
       echo "Bucket creation failed"
-      exit 1 
+      exit 1
    fi
-fi  
+fi
 
 
 
@@ -128,62 +128,21 @@ project_label=$(echo ${os_project_name} |  sed -e s/"project_"/""/g)
 
 
 # check connection
-check_swift_connection 
+check_swift_connection
 
 #set read permissions
-read_acl=$(swift stat $bucket | awk '{ if ($1=="Read") if ($2=="ACL:") print $3}' |  sed -e s/"${project_id}:\*"/""/g )  
-read_acl="${project_id}:*,$read_acl"
-swift post "$bucket" -r "${read_acl}"
 
-bnrows=$(swift stat "${bucket}_segments" | wc -l 2> /dev/null )
-if [[ $bnrows -eq 0 ]]; then  
-    echo "Creating bucket: ${bucket}_segments in case over 5 GB files will be uploaded to the bucket."
-    rclone mkdir "${storage_server}:${bucket}_segments"
-fi    
-swift post "${bucket}_segments" -r "${read_acl}" 2> /dev/null
-
-
-#set write permissions
-write_acl=$(swift stat $bucket | awk '{ if ($1=="Write") if ($2=="ACL:") print $3}' |  sed -e s/"${project_id}:\*"/""/g )  
-write_acl="${project_id}:*,$write_acl"
-swift post "$bucket" -w "${write_acl}"
-swift post "${bucket}_segments" -w "${write_acl}" 2> /dev/null
 s3cmd setacl --recursive --acl-grant=all:${project_id} s3://${bucket}
-s3cmd setacl --recursive --acl-grant=all:${project_id} s3://${bucket}_segments
 
 
 echo "----------------------------------------------------------"
-echo "External projects that have read access to bucket $bucket:" 
-swift stat $bucket | awk '{ if ($1=="Read") if ($2=="ACL:") print $3}' | sed -e s/".r:\*"/"Public access"/g | sed -e s/".rlistings,"/""/g | sed -e s/".rlistings"/""/g | tr "," "\n" | tr -d ":,*" | awk '{ print "  "$0}'
+echo "External projects that have read access to bucket $bucket:"
+# swift stat $bucket | awk '{ if ($1=="Read") if ($2=="ACL:") print $3}' | sed -e s/".r:\*"/"Public access"/g | sed -e s/".rlistings,"/""/g | sed -e s/".rlistings"/""/g | tr "," "\n" | tr -d ":,*" | awk '{ print "  "$0}'
+# TODO
 echo "----------------------------------------------------------"
-echo "External projects that have write access to bucket $bucket:" 
-swift stat $bucket | awk '{ if ($1=="Write") if ($2=="ACL:") print $3}' | tr "," "\n" | tr -d ":,*" | awk '{ print "  "$0}'
+echo "External projects that have write access to bucket $bucket:"
+#swift stat $bucket | awk '{ if ($1=="Write") if ($2=="ACL:") print $3}' | tr "," "\n" | tr -d ":,*" | awk '{ print "  "$0}'
+# TODO
 echo "----------------------------------------------------------"
 
 exit
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
-
